/** English copy for web Data Studio (desktop uses i18n). */

const MESSAGES = {
  'common.loading': 'Loading…',
  'nav.soon': 'Soon',
  'chrome.linkAccount': 'Link profile',
  'studio.kicker': 'Rift.lol',
  'studio.title': 'Data Studio',
  'studio.blurb': 'Region-wide League stats hub — precomputed meta tables, not one account’s match history.',
  'studio.home': 'Home',
  'studio.homeExplore': 'Explore ranked statistics across every dimension — from champion picks to pings.',
  'studio.sampleNote': '{platform} · {n} ranked players in distribution',
  'studio.sampleNoteMatches': '{platform} · {n} matches in this table',
  'studio.needAccount': 'Link a Riot ID so Data Studio knows which platform/region to query.',
  'studio.metaSoon': 'This view is not in the meta feed yet.',
  'studio.noData': 'No rows in this table yet.',
  'studio.feedUnavailable': 'Unavailable',
  'studio.queue': 'Queue',
  'studio.searchChamp': 'Search for a champion',
  'studio.searchIcon': 'Search for a profile icon',
  'studio.sortIcons': 'Sort icons',
  'studio.sortMostUsed': 'Most used',
  'studio.sortWrHigh': 'Highest WR',
  'studio.sortWrLow': 'Lowest WR',
  'studio.loadMore': 'Load more',
  'studio.rankFilter': 'Rank filter',
  'studio.timeFilter': 'Timeframe',
  'studio.tierEmeraldPlus': 'Emerald+',
  'studio.tierDiamondPlus': 'Diamond+',
  'studio.tierMasterPlus': 'Master+',
  'studio.tierChallenger': 'Challenger',
  'studio.tierGrandmaster': 'Grandmaster',
  'studio.tierPlatinumPlus': 'Platinum+',
  'studio.tierGoldPlus': 'Gold+',
  'studio.tierSilverPlus': 'Silver+',
  'studio.tierIron': 'Iron',
  'studio.time7': '7 days',
  'studio.time14': '14 days',
  'studio.time30': '30 days',
  'studio.groupOverview': 'Overview',
  'studio.groupMatch': 'Match',
  'studio.groupCombat': 'Combat',
  'studio.groupLane': 'Lane & farm',
  'studio.groupLater': 'Mechanics',
  'studio.groupObjectives': 'Objectives',
  'studio.hintIcons': 'Most used across accounts',
  'studio.hintRanks': 'Ranked population by tier',
  'studio.hintLevel': 'Average summoner level',
  'studio.hintBanned': 'Highest ban rates',
  'studio.hintTime': 'Win-rate by time of day',
  'studio.hintDuration': 'Average game length',
  'studio.hintEarly': 'WR delta under 22 minutes',
  'studio.hintLate': 'WR delta over 35 minutes',
  'studio.hintWinSurrender': 'Win via surrender rate',
  'studio.hintLoseSurrender': 'Lose via surrender rate',
  'studio.hintKda': 'Kills / deaths / assists',
  'studio.hintKills': 'Kills per game',
  'studio.hintDeaths': 'Deaths per game',
  'studio.hintFirstBlood': 'First blood rate',
  'studio.hintPentas': 'Pentakills per game',
  'studio.hintCsm': 'CS per minute',
  'studio.hintGold15': 'Gold diff at 15',
  'studio.hintCs15': 'CS at 15',
  'studio.hintXp15': 'XP diff at 15',
  'studio.hintPlates': 'Turret plates taken',
  'studio.hintPings': 'Pings per game',
  'studio.hintDrakes': 'Dragons taken per game',
  'studio.hintSouls': 'Win rate with dragon soul',
  'studio.hintBarons': 'Barons taken per game',
  'studio.hintGrubs': 'Void grubs taken per game',
  'studio.hintRifts': 'Rift heralds taken per game',
  'studio.hintSteals': 'Objective steals per game',
  'studio.rankDist': 'Rank distribution',
  'studio.icons': 'Profile icons',
  'studio.level': 'Summoner level',
  'studio.banned': 'Most banned',
  'studio.time': 'Time of day',
  'studio.duration': 'Game duration',
  'studio.early': 'Early game (<22m)',
  'studio.late': 'Late game (>35m)',
  'studio.winSurrender': 'Win by surrender',
  'studio.loseSurrender': 'Lose by surrender',
  'studio.kda': 'KDA',
  'studio.kills': 'Kills',
  'studio.deaths': 'Deaths',
  'studio.firstBlood': 'First bloods',
  'studio.pentas': 'Pentakills',
  'studio.csm': 'CS/m',
  'studio.gold15': 'Gold diff @ 15',
  'studio.cs15': 'CS @ 15',
  'studio.xp15': 'XP diff @ 15',
  'studio.plates': 'Plates',
  'studio.pings': 'Pings',
  'studio.drakes': 'Drakes',
  'studio.souls': 'Dragon souls',
  'studio.barons': 'Barons',
  'studio.grubs': 'Grubs',
  'studio.rifts': 'Rifts',
  'studio.steals': 'Steals / game',
  'studio.soulsNote': 'Win rate when your team secured the soul · last 30 days.',
  'studio.winRate': 'Win rate',
  'studio.dimension': 'Breakdown',
  'studio.dimChampion': 'Champion',
  'studio.dimRank': 'Rank',
  'studio.dimPlatform': 'Platform',
  'studio.bans': 'Bans',
  'studio.banRate': 'Ban rate',
  'studio.gamesCol': 'games',
  'studio.playersCol': 'players',
  'studio.rankedPlayers': 'ranked players',
  'studio.lpDist': 'LP distribution',
  'studio.lpDistHint': 'Players grouped by cumulative rank score (tier + division).',
  'studio.rankCol': 'Rank',
  'studio.avgGames': 'Avg games',
  'studio.avgWr': 'Avg WR',
  'studio.rankPct': 'Rank %',
  'studio.topPct': 'Top %',
  'studio.night': 'Night',
  'studio.morning': 'Morning',
  'studio.afternoon': 'Afternoon',
  'studio.evening': 'Evening',
  'studio.champCol': 'Champion',
  'studio.blue': 'Blue',
  'studio.red': 'Red',
  'studio.platform': 'Platform',
};

export function t(key, vars) {
  let out = MESSAGES[key] || key;
  if (vars && typeof out === 'string') {
    out = out.replace(/\{(\w+)\}/g, (_, name) => (
      vars[name] == null ? `{${name}}` : String(vars[name])
    ));
  }
  return out;
}
